# Doesn't work yet - need https://github.com/kubernetes/kubernetes/pull/57320

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: spinnaker
data:
  nginx.conf: |


---

apiVersion: v1
kind: Pod
metadata:
  name: spin-dev-proxy
  namespace: spinnaker
  labels:
    app: spin-dev-proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
      - containerPort: 8000
    volumeMounts:
    - mountPath: /etc/nginx/sites-enabled/
      name: nginx-config
  volumes:
    - name: nginx-config
      configMap:
        name: dev-proxy.conf

---

apiVersion: v1
kind: Service
metadata:
  name: spin-dev-proxy
  namespace: spinnaker
  labels:
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: spin-dev-proxy
